sudo: required

language: node_js

node_js:

- "8"

services:
  - docker

before_install:
  - docker build -t adamzyga/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adamzyga/docker-react npm run test -- --coverage